### PR TITLE
Accept max_messages param

### PR DESCRIPTION
**Pull request by k-bx**
Also upgrades signal cli to 0.12.1 since it failed to build previously (couldn't find signal-cli-native of 0.12.0).

Contributes towards https://github.com/bbernhard/signal-cli-rest-api/issues/365

### CODE REVIEW

**Comment by k-bx** [comment]
One thing to note on this. This worked on my Docker macOS arm64, but failed on prod Ubuntu x86_64 machine with:

```
WARN  Manager - Failed to call libsignal-client: Can't load library: /tmp/1243969752656717
```

I wanted to try out newer LIBSIGNAL_CLIENT_VERSION=0.30.0 but couldn't find where I can get the files for ext/libraries/libsignal-client/v0.31.0.

Possibly relevant https://github.com/AsamK/signal-cli/issues/1305

**Comment by bbernhard** [comment]
Many thanks for the PR!

I'll wait until the CI is finished, but to me it looks good!

Regarding your issues: Which mode did you use on your x86-64 machine? the native mode?

regarding libsignal-client v0.31.0: I always try to stay at the same version that signal-cli comes packaged with. Newer versions might work, but I think it is the safest approach to use the same version as the pre-packaged signal-cli :)

**Comment by k-bx** [comment]
You're welcome!

> Regarding your issues: Which mode did you use on your x86-64 machine? the native mode?

Native mode

> regarding libsignal-client v0.31.0: I always try to stay at the same version that signal-cli comes packaged with. Newer versions might work, but I think it is the safest approach to use the same version as the pre-packaged signal-cli :)

Gotcha. Where do you see which version it's packaged with?

**Comment by k-bx** [comment]
One thing I forgot to mention, I would very much appreciate if you'd ping me once this is on Docker Hub. I think it might be something with my image being built differently so I'd love to try out the "official" build.

**Comment by bbernhard** [comment]
> Native mode

ok, then it could indeed be GraalVM related.

> Gotcha. Where do you see which version it's packaged with?

It is mentioned in the signal-cli release [changelog](https://github.com/AsamK/signal-cli/blob/master/CHANGELOG.md) and verified again in the [dockerfile](https://github.com/bbernhard/signal-cli-rest-api/blob/master/Dockerfile#L108).

> One thing I forgot to mention, I would very much appreciate if you'd ping me once this is on Docker Hub. I think it might be something with my image being built differently so I'd love to try out the "official" build.

I'll try, if I do not forget. You can btw. also watch this github repository for a new release (see https://github.blog/changelog/2018-11-27-watch-releases/). I'll always create a new github release when a new release is ready and the image is pushed to dockerhub. But maybe I can get docker image up for beta testing sooner, in that case I'll let you know :)

**Comment by k-bx** [comment]
I’m watching all commits and releases so should be good :)

**Comment by mattwr18** [comment]
I was just creating a ticket for this issue. We have been testing out the `0.68-pre` release and ran into this issue in native mode.

**Pull request merged**
